apiVersion: v1
kind: Service
metadata:
  name: nodeport-service-2
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001 # A specific port in the range 30000-32767
  type: NodePort