apiVersion: v1          
kind: Pod              
metadata:              
  name: my-pod-1     
  labels:               
    app: my-demo       
spec:                   
  containers:           
    - name: my-container 
      image: httpd

---

apiVersion: v1
kind: Service
metadata:
  name: my-service-1
spec:
  selector:
    app: my-app
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30002
  type: NodePort


---

apiVersion: v1
kind: Service
metadata:
  name: my-service-1
spec:
  selector:
    app: my-app
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30004
  type: NodePort